### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by thuanpv** [sunbeam891/Smart_contract_fuzzing#1]
Hi Shubham,

I got the following error while trying to build the code by running " ./Build_all.sh"

./Build_all.sh: line 8: cd: Scripts_main: No such file or directory
chmod: cannot access 'Requirements_install.sh': No such file or directory
sudo: ./requirements_install.sh: command not found
script_edit_6: Pulling from saddie/confuzzius
Digest: sha256:a96a004069833ae2b3bcecde2061f039f76031ffb95298f006307065e6509418
Status: Image is up to date for saddie/confuzzius:script_edit_6
docker.io/saddie/confuzzius:script_edit_6
script_edit_6: Pulling from saddie/ilf
Digest: sha256:19826784b4e2fb5a9c25079b7b52b5760f451caab7683f022d18a59280d90ee9
Status: Image is up to date for saddie/ilf:script_edit_6
docker.io/saddie/ilf:script_edit_6
invalid reference format: repository name must be lowercase

Could you please take a look? I tested the command on Ubuntu 18.04.

Thanks.

**Comment by sunbeam891** [comment]
Hi Thuan, I have fixed the issue from my side and have tested it on a fresh installation of Ubuntu 18.04. Please have a look. 
Thanks

**Comment by thuanpv** [comment]
The build is successful now but I get this error while running "./exec_file.sh $PFBENCH Confuzzius 3"

CONFUZZIUS: Fuzzing in progress ...
CONFUZZIUS: Waiting for the following containers to stop:  7a53b2e38263 c2c82d30d4bf ae753ac0cfd2Collecting results and performing necessary operations ..... Traceback (most recent call last):
  File "/home/ubuntu/Smart_contract_fuzzing/Scripts_main/Result_present.py", line 223, in <module>
    plt.show()
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 254, in show
    return _show(*args, **kw)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 218, in show
    cls.mainloop()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 1078, in mainloop
    Tk.mainloop()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 560, in mainloop
    _default_root.tk.mainloop(n)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
